version = 1

[[annotations]]
path = "*"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "mzs_tools/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "mzs_tools/data/CdI_Tabelle_4.2.mdb"
SPDX-FileCopyrightText = [
  "2021 Commissione tecnica per la microzonazione sismica",
  "2021 In-Time"
]
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "mzs_tools/plugin_utils/logging.py",
  "mzs_tools/plugin_utils/settings.py"
]
SPDX-FileCopyrightText = [
    "2022-2026 Oslandia <qgis@oslandia.com>",
    "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
]
SPDX-License-Identifier = [
    "MIT",
    "GPL-3.0-or-later"
]

[[annotations]]
path = "mzs_tools/ext_libs/ucanaccess-5.1.5-uber.jar"
SPDX-FileCopyrightText = "2012-2026 UCanAccess Project Authors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "mzs_tools/resources/**"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "help/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "docs/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = ".vscode/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "docker/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"

[[annotations]]
path = "tests/**"
SPDX-FileCopyrightText = "2018-2026 CNR-IGAG LabGIS <labgis@igag.cnr.it>"
SPDX-License-Identifier = "GPL-3.0-or-later"
